console:
  max_message_size_bytes: 409600
logger:
  level: "INFO"
runtime:
  js_entrypoint: "build/index.js"
session:
  token_expiry_sec: 9600 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072